#pragma once

namespace ember::platform {
    enum class mouse_button {
        none,
        undefined,

        _1,
        _2,
        _3,
        _4,
        _5,

        left   = _1,
        right  = _2,
        middle = _3,
    };

    enum class key {
        none,
        undefined,

        //Regular keys
        space,
        apostrophe,
        comma,
        minus,
        period,
        slash,
        _0,
        _1,
        _2,
        _3,
        _4,
        _5,
        _6,
        _7,
        _8,
        _9,
        semicolon,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        bracket_left,
        bracket_right,
        back_slash,
        grave_accent,

        //Functions keys
        escape,
        enter,
        tab,
        backspace,
        insert,
        del,
        right,
        left,
        down,
        up,
        page_up,
        page_down,
        home,
        end,
        caps_lock,
        scroll_lock,
        num_lock,
        print_screen,
        pause,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        num_pad_0,
        num_pad_1,
        num_pad_2,
        num_pad_3,
        num_pad_4,
        num_pad_5,
        num_pad_6,
        num_pad_7,
        num_pad_8,
        num_pad_9,
        num_pad_decimal,
        num_pad_divide,
        num_pad_multiply,
        num_pad_subtract,
        num_pad_add,
        shift_left,
        shift_right,
        control_left,
        control_right,
        alt_left,
        alt_right,
        super_left,
        super_right,
    };
}